### ISSUE TITLE
Request contains an invalid argument.

### ISSUE THREAD

**Issue by frelev** [ynot123/LMS_Controls#15]
When I click "See how it works in Google Assistant" I get

Request contains an invalid argument.
Query pattern is missing for custom intent 'play_playlist'

**Comment by frelev** [comment]
Found the reason for this. It doesn't work when Swedish is added. I removed SV and then its all good

**Comment by frelev** [comment]
This is however a pity since I cannot then enable "swedish" in Google Assistant for voice control: "Application does not support sv"

**Comment by ynot123** [comment]
Looking, at it seems Dialogflow supports Swedish.  Is it a Google assistant problem?  I do see that (in Canada at least) Google Assistant appears to support Swedish.  Click setup, invocation and on the right there is a modify language selection and Swedish is near the bottom.  Did you give that a shot?

If I get a chance in the new few weeks, perhaps I can try French to see how that goes.

Otherwise you can try the other user here that was attempting Italian, finally you can reach out to users at the logitech forum to see if any have done translations.  https://forums.slimdevices.com/showthread.php?109273-Announce-LMS-Controls-Google-Home-Google-Assistant-Voice-Control-of-LMS-Players

Ynot.

**Comment by frelev** [comment]
Hi. Yes both GA and Dialogflow supports Swedish,. The issue I`m facing is that if I add Swedish to Dialogflow I cannot publish the app to GA. 

![dialog](https://user-images.githubusercontent.com/14004609/52518232-be637500-2c47-11e9-9ca8-e29d1708e51a.png)

![dialog2](https://user-images.githubusercontent.com/14004609/52518234-c9b6a080-2c47-11e9-9915-83e6fd9698f3.png)

If I then remove SV again I can publish it to GA but then I get this when adding Swedish in GA:

![image](https://user-images.githubusercontent.com/14004609/52518281-89a3ed80-2c48-11e9-8dfc-c5dc13867dd8.png)

**Comment by DaveVdb** [comment]
I Have exactly the same issue with translating  to Dutch. 


> "Request contains an invalid argument.
Query pattern is missing for custom intent 'play_playlist'"
